### ISSUE TITLE
Free (Un)Known Designer 

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#219]
Hi guys!

Great work with the recent implementations. OA is evolving more and more professional and works over all the years more and more reliable and satisfactory.
However, with new implemented features few adjustments become necessary/desirable.

For a more convenient and quicker puzzling in the Free (Un)known Designer the following is seen to make sense:
1. Once, all additional figures are selected from the catalogue, they should be kept in the left selection frame with the prescribed figures, as the 1st attempt for the sequence is very often not the optimum solution, which requires modifications in terms of re-ordering the 10 figures or slight modifications of the additiona base-fiures (i.e. negative instead of positive entry and/or exit). Up to date, such modifications require the removal of certain figures and complete reselection from the catalogue.
2. In addition or as an alternative to 1, it should be allowed that single figures within the puzzle box should be re-ordered by drag and drop, which is currently not possible.

Kind regards,
D.

**Comment by OpenAero** [comment]
I'm not sure if this would work and how. There are literally thousands (if not millions) of possible additional figures. Any one of them would be useful in a specific combination but not in most others.
Therefore I think selected additional figures are only useful in the right part, combined with specific figures.
Also, keeping all the additional figures on the left could quickly cram the area up. This would necessitate scrolling and reduce clarity.
The easiest way to build a sequence is by creating multiple combinations on the right part that fit together well and then stitching those together. If unsure of the stitching you can create a copy of the subsequence first.

**Comment by AcroDirki** [comment]
Understand, but what about drag and dropping figures within the right area from one position to another?

**Comment by ptwz** [comment]
Hi there, I've worked on two possible ways to rearrange figures in the editor.

One is in the figure editor, the buttons "<<" and ">>" move the current figure (including Comments, movements, etc) one figure further/back.

The other selecting to figure you want to move and simply start dragging a cross arrow handle left/right of the figure you want put it next to. (note currently there is such thing as a preview or a moving indicator yet, so don't wonder if nothing happens until you drop it).

See http://peter.turczak.de/openaero/ for a demo.

Please let me know your thoughts.

**Comment by OpenAero** [comment]
The demo does look promising. Maybe it would be more simple to have two
blue arrows below a selected figure to move it back or forward. See rough
example image. Ideally this would only be one arrow for the first and last
figure.
Also, moving a figure to the first position should probably remove any
(xx,yy) and [xx,yy] moves as the first figure never has these.

Op di 10 jul. 2018 om 20:44 schreef ptwz <notifications@github.com>:

**Comment by ptwz** [comment]
Well, i tried to implement you suggestion, and for me it becomes very confusing to use. As long as the sequence only had one direction, this is an easy task to do. The arrow pointing right will move the figure further down the sequence when the sequence goes this direction. For example, after a stall turn, this would reverse. So clicking the "same" arrow would lead to a different thing to happen.

When designing a sequence, I find myself shuffeling around the figures quite far and often. So having to follow the figure and always clicking the proper button sometimes can be quite a pain. Especially when 90/270 deg. figure enties/exits are planned.

Therefore dragging the figure seems much more natural and easier for a user to understand. Otherwise having arrows in a fixed position, will ensure you understand what it will do at any given click but leads to more screen clutter.

**Comment by OpenAero** [comment]
@ptwz The issue now discussed is different from the one in the Free Designer, for which this issue was started. Please continue in Issue #232
